dockerImageAndWorkDir: &dockerImageAndWorkDir
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo

version: 2.1
jobs:
  install-dependencies:
    <<: *dockerImageAndWorkDir
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace: 
          root: ~/repo
          paths:
            - .

  test:
    <<: *dockerImageAndWorkDir
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Running testcases'
          command: yarn test

  lint:
    <<: *dockerImageAndWorkDir
    steps:
      - attach_workspace:
          at: ~/user-ms
      - checkout
      - restore_cache:
          keys:
          - v1-{{checksum "package-lock.json"}}
      - run:
          name: 'Running eslint'
          command: npm run lint

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - lint:
          requires:
              - install-dependencies
      - test:
          requires:
              - install-dependencies