dockerImageAndWorkDir: &dockerImageAndWorkDir
    docker:
        - image: circleci/node:10.0.0
    working_directory: ~/repo

version: 2.1

commands:
    get-code:
        steps:
            - attach_workspace:
                at: ~/repo
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}

jobs:
    install-dependencies:
        <<: *dockerImageAndWorkDir
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace: 
                root: ~/repo
                paths:
                    - .

    test:
        <<: *dockerImageAndWorkDir
        steps:
            - get-code
            - run:
                name: 'Running testcases'
                command: yarn test

    lint:
        <<: *dockerImageAndWorkDir
        steps:
            - get-code
            - run:
                name: 'Running eslint'
                command: yarn lint

    build:
        <<: *dockerImageAndWorkDir
        steps:
            - get-code
            - run:
                name: 'Create build'
                command: yarn build

    dockerize:
        <<: *dockerImageAndWorkDir
        steps:
            - get-code
            - run:
                name: 'Create docker image'
                command: docker build -t react-app .


workflows:
    version: 2
    test-and-build:
        jobs:
            - install-dependencies
            - lint:
                requires:
                    - install-dependencies
            - test:
                requires:
                    - install-dependencies
            - build:
                requires:
                    - lint
                    - test
                filters:
                    branches:
                        only:
                            - 'feature/circle-ci'
            - dockerize:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - 'feature/circle-ci'